### ISSUE TITLE
General improvements request

### ISSUE THREAD

**Issue by rockerroller** [teravoz/react-webrtc-adapter#3]
## General

All methods and events must be camel-case (hangup to hangUp, for instance).

## Method: `register`

pass the username and the password as arguments, not as object properties.
remove the promise

## Method: `dial`

remove the object-like arugment and pass only the number as argument
in case of dialing error, emit an event instead of invoking a callback.

## Event: on `incomingCall`

returns only the `theirNumber` as the callback argument.
the handler should be handled by the lib and exposed as root methods such as `teravoz.accept()` and `teravoz.decline()`.

## Event: on `DTMF`

must return nothing.
the `sendTones` function should be handled by the lib and exposas as a root method `teravoz.sendTone(tone)`.

**Comment by rikez** [comment]
Working on it bro!

**Comment by rikez** [comment]
Improved most of the things on v1
